In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_chroma import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings

In [2]:
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
import pandas as pd

In [4]:
books = pd.read_csv("books_cleaned.csv")

In [5]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [6]:
books["tagged_description"].to_csv("tagged_description.txt", sep="\n", index=False,header=False)

In [7]:
max_len = books["tagged_description"].str.len().max()
print(max_len)  # use this as chunk_size

5800

In [8]:
raw_documents = TextLoader("tagged_description.txt",encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=6000,chunk_overlap=0,separator="\n")
documents = text_splitter.split_documents(raw_documents)

In [9]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.\n9780002261982 A new \'Christie for Christmas\' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. \'Supposing I were to come down one morning and find a dead body in the library, what should I do?\' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER\'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI\n9780006178736 A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia\'s schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power.\n9780006280897 Lewis\' work on the nature of love divides love into four categories; Affection, Friendship, Eros and Charity. The first three come naturally to humanity. Charity, however, the Gift-love of God, is divine, and without this supernatural love, the natural loves become distorted and even dangerous.\n"9780006280934 ""In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors and thinkers, examines a universally applicable question within the human condition: If God is good and all-powerful, why does he allow his creatures to suffer pain? With his signature wealth of compassion and insight, C.S. Lewis offers answers to these crucial questions and shares his hope and wisdom to help heal a world hungering for a true understanding of human nature.""--Amazon."\n9780006380832 Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall\'s history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition.\n9780006470229 A new-cover reissue of the fourth book in the bestselling five-volume sf series created by the world-famous author of the Thomas Covenant chronicles -- and acclaimed as the \'best work of his career\'. Events were not moving as the Amnion had intended. Once again humans had been false in their dealings with the aliens. As the planetoid Thanatos Minor exploded into atoms, the Trumpet hurtled into space only one step ahead of hostile pursuers. On board were Morn Hyland and her force-grown son Davies, cyborg Angus Thermopyle and Captain Nick Succorso -- old enemies thrown together in a desperate bid for survival. For both the Amnion and the UMCP, the immediate capture of the fleeing ship and the secrets it contained was imperative. But for Trumpet\'s exhausted crew the only hope lay in an illegal lab in the distant binary solar system of Valdor Industrial. It would be a journey of unpredictable danger -- from which not all would return...\n9780006472612 Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.')

In [10]:
print(len(documents))

468

In [11]:
import os
from langchain_community.vectorstores import Chroma
import time

embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-001",
    google_api_key=os.getenv("VERTEX_AI_API_KEY")
)

BATCH_SIZE = 10
db_books = Chroma.from_documents(documents[:BATCH_SIZE], embedding=embeddings, persist_directory="book_db")

for i in range(BATCH_SIZE, len(documents), BATCH_SIZE):
    batch = documents[i:i + BATCH_SIZE]
    db_books.add_documents(batch)
    time.sleep(1)
    print(f"Processed {min(i + BATCH_SIZE, len(documents))}/{len(documents)} docs")

db_books.persist()
print("Done! chroma_db/ folder is ready.")

Processed 20/468 docs
Processed 30/468 docs
Processed 40/468 docs
Processed 50/468 docs
Processed 60/468 docs
Processed 70/468 docs
Processed 80/468 docs
Processed 90/468 docs
Processed 100/468 docs
Processed 110/468 docs
Processed 120/468 docs
Processed 130/468 docs
Processed 140/468 docs
Processed 150/468 docs
Processed 160/468 docs
Processed 170/468 docs
Processed 180/468 docs
Processed 190/468 docs
Processed 200/468 docs
Processed 210/468 docs
Processed 220/468 docs
Processed 230/468 docs
Processed 240/468 docs
Processed 250/468 docs
Processed 260/468 docs
Processed 270/468 docs
Processed 280/468 docs
Processed 290/468 docs
Processed 300/468 docs
Processed 310/468 docs
Processed 320/468 docs
Processed 330/468 docs
Processed 340/468 docs
Processed 350/468 docs
Processed 360/468 docs
Processed 370/468 docs
Processed 380/468 docs
Processed 390/468 docs
Processed 400/468 docs
Processed 410/468 docs
Processed 420/468 docs
Processed 430/468 docs
Processed 440/468 docs
Processed 450/468 docs
Processed 460/468 docs
Processed 468/468 docs
Done! chroma_db/ folder is ready.

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_8216\3709474406.py:19: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  db_books.persist()

In [12]:
query = "A book to teach children about Nature"

docs = db_books.similarity_search(query,k=10)

docs

[Document(metadata={'source': 'tagged_description.txt'}, page_content='9780064472777 Top Ten Reasons Samantha Madison is in Deep Trouble 10. Her big sister is the most popular girl in school 9. Her little sister is a certified genius 8. She\'s in love with her big sister\'s boyfriend 7. She got caught selling celebrity portraits in school 6. And now she\'s being forced to take art classes 5. She\'s just saved the president of the United Statesfrom an assassination attempt 4. So the whole world thinks she is a hero 3. Even though Sam knows she is far, far from being a hero 2. And now she\'s been appointed teen ambassador to the UNAnd the number-one reason Sam\'s life is over?1. The president\'s son just might be in love with her\n9780064473552 Strange things happen at Hexwood Farm. From her window, Ann Stavely watches person after person disappear through the farm\'s gate -- and never come out again. Later, in the woods nearby, she meets a tormented sorcerer, who seems to have arisen from a centuries-long sleep. But Ann knows she saw him enter the farm just that morning. Meanwhile, time keeps shifting in the woods, where a small boy -- or perhaps a teenager -- has encountered a robot and a dragon. Long before the end of their adventure, the strangeness of Hexwood has spread from Earth right out to the center of the galaxy.\n9780066236179 Last night while I lay thinking here Some Whatifs crawled inside my ear And pranced and partied all night long And sang their same old Whatif song: Whatif I flunk that test? Whatif green hair grows on my chest? Whatif nobody likes me? Whatif a bolt of lightning strikes me?... To celebrate its 20th anniversary, Shel Silverstein\'s A Light in the Attic is now available in a special edition containing the classic hardcover book and a CD of highlights from his Grammy Award-winning album. Here in the attic of Shel Silverstein you will find Backward Bill, Sour Face Ann, the Meehoo with an Exactlywatt, and the Polar Bear in the Frigidaire. You will talk with Broiled Face, and find out what happens when Somebody steals your knees, you get caught by the Quick-Digesting Gink, a Mountain snores, and They Put a Brassiere on the Camel. From the creator of the beloved poetry collections Where the Sidewalk Ends and Falling Up, here is another wondrous book of poems and drawings.\n9780066238500 Journeys to the end of the world, fantastic creatures, and epic battles between good and evil -- what more could any reader ask for in one book? The book that has it all is The Lion, the Witch and the Wardrobe, written in 1949 by Clive Staples Lewis. But Lewis did not stop there. Six more books followed, and together they became known as The Chronicles of Narnia. For the past fifty years, The Chronicles of Narnia have transcended the fantasy genre to become part of the canon of classic literature. Each of the seven books is a masterpiece, drawing the reader into a land where magic meets reality, and the result is a fictional world whose scope has fascinated generations. This edition presents all seven books -- unabridged -- in one impressive volume. The books are presented here according to Lewis\' preferred order, each chapter graced with an illustration by the original artist, Pauline Baynes. Deceptively simple and direct, The Chronicles of Narnia continue to captivate fans with adventures, characters, and truths that speak to readers of all ages, even fifty years after they were first published.\n9780066620107 What Would Machiavelli Do? He would feast on other people\'s discord He wouldn\'t exactly seek the company of ass-kissers and bimbos, but he wouldn\'t reject them out of hand either He would realize that loving yourself means never having to say you\'re sorry He would kill people, but only if he could feel good about himself afterward He would establish and maintain a psychotic level of control He would use other people\'s opinions to sell his book!\n"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."'),
 Document(metadata={'source': 'tagged_description.txt'}, page_content='9780062508867 This vivid and detailed biography strips away centuries of distortion and myth and presents a balanced view of the man whose religion continues to dramatically affect the course of history.\n9780062511119 The essence of perennial Stoic wisdom in aphorisms of stunning insight and simplicity. The West\'s first and best little instruction book offers thoroughly contemporary and pragmatic reflections on how best to live with serenity and joy.\n9780062512796 Previously published as The Diary of a Magus, this book tells of Coelho\'s initiation into a spiritual path, leading to inner development and wisdom. He shares exercises in self-control and self-discovery, which he was taught on his pilgrimage along the ancient road to Santiago.\n"9780062513342 A Magical Tale About Forgiving Our Past and Believing in Our Future The enchanting, true story of The Valkyries begins in Rio de Janeiro when author Paulo Coelho gives his mysterious master J., the only manuscript for his book The Alchemist. Haunted by a devastating curse, Coelho confesses to J., ""I′ve seen my dreams fall apart just when I seemed about to achieve them."" In response, J. gives Coelho a daunting task: He must find and speak with his guardian angel. ""The curse can be broken,"" he replies, ""if you complete the task."" Rising to the challenge, Paulo and his wife, Cristina, drop everything, pack their bags, and take off on a forty day adventure into the starkly beautiful and sometimes dangerous Mojave Desert where they encounter more than they bargained for. A masterful blend of the exotic locales, dramatic adventure, and magical storytelling, for which Coelho′s fictional works are renowned, this true-life account is at once a modern-day adventure and a metaphysical odyssey."\n9780062516374 Rainforest Healing from Your Home and Garden Find alternatives to chemical anti-depressants and painkillers in your spice rack. Learn about natural anti-itch salves for insect bites. Soothe and relieve envy, grief, sadness, and fear the Maya way. Rid your house of negative energy with a Maya cleansing ritual. Try the easy-to-make bronchitis remedy.\n9780062700254 A beautiful gift edition of Thomas Bulfinch\'s classic retelling of famous myths and folk legends, with interpretive essays by Princeton classics professor Richard P. Martin.\n9780064400961 Best Friends Forever There are lots of children on Hill Street, but no little girls Betsy\'s age. So when a new family moves into the house across the street, Betsy hopes they will have a little girl she can play with. Sure enough, they do—a little girl named Tacy. And from the moment they meet at Betsy\'s fifth birthday party, Betsy and Tacy becoms such good friends that everyone starts to think of them as one person—Betsy-Tacy. Betsy and Tacy have lots of fun together. They make a playhouse from a piano box, have a sand store, and dress up and go calling. And one day, they come home to a wonderful surprise—a new friend named Tib. Ever since their first publication in the 1940\'s, the Betsy-Tacy stories have been loved by each generation of young readers.\n9780064400992 Betsy, Tacy, and Tib can\'t wait to be ten. After all, getting two numbers in your age is the beginning of growing up—exciting things are bound to happen. And they do! The girls fall in love with the King of Spain, perform in the School Entertainment, and for the first time, go all the way over the Big Hill to Little Syria by themselves. There Betsy, Tacy, and Tib make new friends and learn a thing or two. They learn that new Americans are sometimes the best Americans. And they learn that they themselves wouldn\'t want to be anything else. Ever since their first publication in the 1940s, the Betsy-Tacy stories have been loved by each generation of young readers.\n9780064401685 When a strange little man comes to the Coven Tree Church Social promising he can give people exactly what they ask for, three young believers-in-magic each make a wish that comes true in the most unexpected way.\n9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author\'s father].\' \'BL. 1986 Children\'s Editors\' Choices (BL) Children\'s Choices for 1987 (IRA/CBC) Notable 1986 Childrens\' Trade Books in Social Studies (NCSS/CBC) 1986 Children\'s Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)\n9780064403368 Twelve-year-old Casey is waiting for the day that Barney, her father, hits it big -- \'cause when that horse comes in, he tells her, it\'s the penthouse suite. But then hr ends up in the hospital, and Casey is sent to Chinatown to live with her grandmother, Paw-Paw. Now the waiting seems longer than ever. Casey feels lost in Chinatown. She\'s not prepared for the Chinese school, the noisy crowds, missing her father. But Paw-Paw tells her about the mother Casey never knew, and about her family\'s owl charm and her true Chinese name. And Casey at last begins to understand that this -- Paw-Paw\'s Chinatown home, her parents\' home -- is her home,too.\n9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award'),
 Document(metadata={'source': 'tagged_description.txt'}, page_content='9780688172244 Kent Weeks made international headlines when, seventy feet below the surface of Egypt\'s Valley of the Kings he found the largest and most complicated mausoleum yet discovered, the tomb of Ramesses II\'s sons. Now for the first time, Weeks shares up-to-the-minute details on the thrilling discovery and contemplates what the tomb, called KV5, will reveal as the excavation moves forward. Built in the age of Exodus, the tomb could potentially transform ancient and biblical history. Its lower levels, possibly containing mummies of Ramesses II\'s sons, may shed new light on many of the mysteries of the Old Testament, including the story of Moses and the flight of the Israelites from Egypt. Weeks draws on his own diaries, as well as those of his wife and his foreman, to describe the excitement and risks that surround such a significant find. From floodwaters that threatened the opened tomb and the precarious craw spaces deep within it, to thieving tourists and scorpions, this adventure is not for the weak of heart. Photographs and sketches illustrate the crew\'s progress and the objects and decorations found in the tomb\'s chambers and hallways The result a true-life, impossibly thrilling Raiders of the Lost Arkwill entrance readers from beginning to end.\n9780689707490 The beloved, bestselling tale of edible weather is brought to life! If food dropped like rain from the sky, wouldn\'t it be marvelous! Or would it? It could, after all, be messy. And you\'d have no choice. What if you didn\'t like what fell? Or what if too much came? Have you ever thought of what it might be like to be squashed flat by a pancake?\n"9780689716041 An eight-year-old boy who is frightened of traveling over Hemlock Mountain overcomes his fear by taking the trip while chanting, ""There are no bears on Hemlock Mountain,"" in a suspenseful tale. Reissue."\n"9780689802171 Third grader Marâia Isabel, born in Puerto Rico and now living in the United States, wants badly to fit in at school; and the teacher\'s writing assignment ""My Greatest Wish"" gives her that opportunity."\n9780689822841 Hitty is a doll of great charm and character. It is indeed a privilege to publish her memoirs, which, besides being full of the most thrilling adventures on land and sea, also reveal her delightful personality. One glance at her portrait will show that she is no ordinary doll. Hitty, or Mehitable as she was really named, was made in the early 1800s for Phoebe Preble, a little girl from Maine. Young Phoebe was very proud of her beautiful doll and took her everywhere, even on a long sailing trip in a whaler. This is the story of Hitty\'s years with Phoebe, and the many that follow in the life of a well-loved doll.\n9780689823824 Here is a delightful look at childhood, written by master poet and storyteller Robert Louis Stevenson. In this collection of sixty-six poems, Stevenson recalls the joys of his childhood, from sailing boats down a river, to waiting for the lamplighter, to sailing off to foreign lands in his imagination. Tasha Tudor\'s watercolor paintings evoke a simpler time in the past, and celebrate two of the things she loves most -- children and nature. Her talents are the perfect match for these inspiring poems, making this a handsome gift edition that will be cherished by families for generations.\n9780689833762 Knock, knock. Who\'s there? Someone with sad underwear. Sad underwear? How can that be? When my best friend\'s mad at me, Everything is sad. Even my underwear. Only Judith Viorst, with the perfect pitch for the trials of childhood that has made her Alexander books modern classics, could create an ode to melancholy unmentionables. But the title poem is just one of the many pleasures in this collection, which bursts with wit and understanding -- and the occasional poignant note. Sure to delight readers of Shel Silverstein and Jack Prelutsky, as well as Viorst\'s own legions of fans, Sad Underwear is a perfect companion volume to her celebrated If I Were In Charge of the World.\n9780689834196 Young Michael Jordan, who is smaller than the other players, learns that determination and hard work are more important than size when playing the game of basketball.\n9780689835612 Is Mommy behind the chair? Is Mommy behind the plant? Join baby as he plays hide-and-seek with Mommy. The sturdy format and easy-to-lift flaps in this delightful interactive book are perfect for parents and children to share.\n9780689840333 The Dark is rising in its last and greatest bid to control the world. And Will Stanton -- last-born of the immortal Old Ones, dedicated to keeping the world free -- must join forces with this ageless master Merriman and Bran, the Welsh boy whose destiny ties him to the Light. Drawn in with them are the three Drew children, who are mortal, but have their own vital part in the story. These six fight fear and death in the darkly brooding Welsh hills, in a quest through time and space that touches the most ancient myths of the British Isles, and that brings Susan Cooper\'s masterful sequence of novels to a satysfying close.'),

In [13]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
437,9780064472777,0064472779,All-American Girl,Meg Cabot,Juvenile Fiction,http://books.google.com/books/content?id=Fktx5...,Top Ten Reasons Samantha Madison is in Deep Tr...,2003.0,3.74,398.0,58422.0,All-American Girl,9780064472777 Top Ten Reasons Samantha Madison...

In [14]:
def get_semantic_recommendation(
        query:str,
        top_k:int = 10,
)->pd.DataFrame:
    recs = db_books.similarity_search(query,k=40)

    books_list = []

    import re
    books_list = [int(re.search(r'\d+', rec.page_content.split()[0]).group()) for rec in recs]

    return books[books["isbn13"].isin(books_list)].head(top_k)

In [15]:
get_semantic_recommendation("A book to teach children about Nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
76,9780007204465,0007204469,Tropic of Cancer,Henry Miller,Fiction,http://books.google.com/books/content?id=ProgR...,"Miller's groundbreaking first novel, banned in...",2005.0,3.69,336.0,709.0,Tropic of Cancer,9780007204465 Miller's groundbreaking first no...
97,9780060090371,0060090375,Lucy Sullivan Is Getting Married,Marian Keyes,Fiction,http://books.google.com/books/content?id=qLl-3...,What happens when a psychic tells Lucy that sh...,2002.0,3.76,640.0,42096.0,Lucy Sullivan Is Getting Married,9780060090371 What happens when a psychic tell...
105,9780060256579,0060256575,The Missing Piece Meets the Big O,Shel Silverstein,Juvenile Fiction,http://books.google.com/books/content?id=-m4gw...,The missing piece sat alone waiting for someon...,1981.0,4.33,104.0,10010.0,The Missing Piece Meets the Big O,9780060256579 The missing piece sat alone wait...
315,9780060936662,0060936665,Smart Discipline(R),Larry Koenig,Family & Relationships,http://books.google.com/books/content?id=Bpo2r...,"Larry J. Koenig, Ph.D., creator of the hugely ...",2004.0,3.99,208.0,12.0,"Smart Discipline(R): Fast, Lasting Solutions f...","9780060936662 Larry J. Koenig, Ph.D., creator ..."
385,9780061150142,0061150142,The Pact,Jodi Picoult,Fiction,http://books.google.com/books/content?id=VDCvq...,Until the phone calls came at three o'clock on...,2006.0,4.01,512.0,237587.0,The Pact: A Love Story,9780061150142 Until the phone calls came at th...
395,9780062508867,0062508865,Muhammad,Karen Armstrong,Biography & Autobiography,http://books.google.com/books/content?id=FbDVD...,This vivid and detailed biography strips away ...,1993.0,4.15,304.0,4795.0,Muhammad,9780062508867 This vivid and detailed biograph...
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,The Rainbow People,"9780064404419 ""Culled from 69 stories collecte..."
420,9780064408677,0064408671,The Trumpet of the Swan,E. B. White,Juvenile Fiction,http://books.google.com/books/content?id=2lybT...,"Swan Song Like the rest of his family, Louis i...",2000.0,4.07,252.0,61304.0,The Trumpet of the Swan,9780064408677 Swan Song Like the rest of his f...
430,9780064435260,0064435261,A Little Prairie House,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=pRSju...,"Long, long ago, a little girl named Laura Inga...",1999.0,4.19,32.0,1533.0,A Little Prairie House,"9780064435260 Long, long ago, a little girl na..."
437,9780064472777,0064472779,All-American Girl,Meg Cabot,Juvenile Fiction,http://books.google.com/books/content?id=Fktx5...,Top Ten Reasons Samantha Madison is in Deep Tr...,2003.0,3.74,398.0,58422.0,All-American Girl,9780064472777 Top Ten Reasons Samantha Madison...